apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: exchange-settlement-prod
namespace: app-prod
resources:
  - ../../base
  - pdb.yaml # ⭐ Prod 전용: Pod Disruption Budget
  - hpa.yaml
commonLabels:
  environment: prod
patches:
  - path: patches/namespace.yaml 
  - path: patches/deployment.yaml
  - path: patches/ingress.yaml
  - path: patches/externalsecret.yaml
images:
  - name: app
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/exchange-settlement-app
    newTag: latest-prod
